version: "3.3"

services:

  PostgresDatabase:
    image: postgres:11.2
    container_name: PostgresDatabase
    hostname: PostgresDatabase
    environment:
      - POSTGRES_PASSWORD=rootroot
      - POSTGRES_USER=dbo_admin
      - POSTGRES_DB=test_db
    ports:
      - 5432:5432
    networks:
      - TestNetwork

networks:
  TestNetwork:

